stages:
  - build

.test_template: &distro_test
  script:
    - export LC_ALL=C.UTF-8
    - meson . _build -Dgtk_doc=true
    - ninja -C _build
    - ninja -C _build meson-libhandy-doc 2>&1 | tee _build/doc/buildlog
    # Check gtk-doc did not produce any new warnings
    - "! grep -qs 'warning' _build/doc/buildlog"
    - xvfb-run ninja -C _build test

.tags_template: &distro_tags
  tags:
    - librem5

build-debian:
  image: debian:buster
  <<: *distro_tags
  before_script:
    - apt-get -y update
    - apt-get -y install build-essential libgtk-3-doc
    - apt-get -y build-dep .
  stage: build
  <<: *distro_test

build-fedora:
  image: fedora:28
  <<: *distro_tags
  before_script:
    - dnf -y update
    - dnf -y install @development-tools xvfb-run gtk-doc gobject-introspection-devel gnome-desktop-devel gtk3-devel meson pkg-config vala-devel
  stage: build
  <<: *distro_test
