stages:
  - build

build-debian:
  image: debian:buster
  tags:
    - librem5
  before_script:
    - apt-get -y update
    - apt-get -y install build-essential libgtk-3-doc lcov
    - apt-get -y build-dep .
  stage: build
  script:
    - export LC_ALL=C.UTF-8
    - meson . _build -Dgtk_doc=true -Db_coverage=true --werror
    - ninja -C _build
    - ninja -C _build meson-libhandy-doc 2>&1 | tee _build/doc/buildlog
    # Check gtk-doc did not produce any new warnings
    - "! grep -qs 'warning' _build/doc/buildlog"
    - xvfb-run ninja -C _build test
    - ninja -C _build coverage
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'
  artifacts:
    when: always
    paths:
      - _build

build-flatpak:
  stage: build
  tags:
    - librem5
  image: debian:buster
  variables:
    app_id: "sm.puri.Handy.Example"
  artifacts:
    paths:
      - "${app_id}-dev.flatpak"
    expire_in: 1 day
  before_script:
    - apt-get -y update
    - apt-get -y install flatpak flatpak-builder
    - flatpak remote-add --if-not-exists gnome-nightly https://sdk.gnome.org/gnome-nightly.flatpakrepo
    - flatpak install -y gnome-nightly org.gnome.Sdk master
    - flatpak install -y gnome-nightly org.gnome.Platform master
  script:
    - bash -x .gitlab-ci/flatpak-build.sh "${app_id}"
