stages:
  - build

build-debian:
  image: debian:buster
  tags:
    - librem5
  before_script:
    - apt-get -y update
    - apt-get -y install build-essential libgtk-3-doc
    - apt-get -y build-dep .
  stage: build
  script:
    - export LC_ALL=C.UTF-8
    - meson . _build -Dgtk_doc=true --werror
    - ninja -C _build
    - ninja -C _build meson-libhandy-doc 2>&1 | tee _build/doc/buildlog
    # Check gtk-doc did not produce any new warnings
    - "! grep -qs 'warning' _build/doc/buildlog"
    - xvfb-run ninja -C _build test

