#!/usr/bin/python3
#
# Make sure gobject introspection works

import gi

gi.require_version('Handy', '1')
from gi.repository import Handy

keypad = Handy.Keypad()

assert keypad.get_name() == 'HdyKeypad'
